services:
  - type: web
    name: iris-fhir
    env: docker
    plan: starter

    dockerContext: Dockerfhir
    dockerfilePath: Dockerfhir/Dockerfile

    autoDeploy: true

    envVars:
      - key: PORT
        value: "52773"

    healthCheckPath: /csp/healthshare/demo/fhir/r4/metadata

    disks:
      - name: iris-fhir-data
        mountPath: /data
        sizeGB: 1
